on:
  issues:
    types: [labeled, edited]
concurrency: 
  group: server-run
  cancel-in-progress: false
jobs:
  run_server:
    if: contains(github.event.issue.labels.*.name, '*start')
    env:
      PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: clone repo locally
      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "microsoft"
      - name: Check eula
        if: !fromJson(github.event.issue.body)['$REQ Do you agree to the Minecraft eula']
        run: |
          echo You must agree to the Minecraft eula.
          echo Edit your issue to reflect that please.
          exit 1
      - run: |
          chmod u+x ./run.sh
          ./run.sh
        name: Run the server
