on:
  workflow_dispatch: 
concurrency: 
  group: server-run
  cancel-in-progress: false
jobs:
  run_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: clone repo locally
      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "microsoft"
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      - name: Install localtunnel
        run: npm i -g localtunnel
      - name: Start Server
        run: |
          chmod u+x ./run.sh
          ./run.sh
