on:
  workflow_dispatch: 
concurrency: 
  group: server-run
  cancel-in-progress: false
jobs:
  run_server:
    env:
      PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: clone repo locally
      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "microsoft"
      - run: |
          chmod u+x ./run.sh
          ./run.sh
        name: Run the server
