on:
  workflow_dispatch:
concurrency:
  group: server-run
  cancel-in-progress: false
jobs:
  run_server:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        name: clone repo locally
      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "microsoft"
      - name: Install remote.it
        run: ${{ secrets.REMOTEIT_COMMAND }}
      - name: Run Server (Long)
        run: ./run.sh
