on:
  issues:
    types: opened
jobs:
  run_server:
    env:
      PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          chmod u+x ./run.sh
          ./run.sh
        name: Install playit and check tunnel status
